# Steel City: Mob Sim — Batch City Asset Generator
# generate_city_assets.py
#
# Reads city_template.json, generates a .stasset file for each business
# in each block, and writes a city_layout.json manifest that the Unity
# StAssetReader + CityMap3D will consume at runtime.
#
# Output:
#   Steel_City-Mob_Sim/Assets/StreamingAssets/voxel_buildings/
#       butcher_0.stasset
#       bakery_0.stasset
#       ...
#   Steel_City-Mob_Sim/Assets/StreamingAssets/city_layout.json

import json
import os
import sys
import numpy as np

# Add VoxelAssetStudio to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from stasset_io import save_stasset
from procedural_mob_buildings import BUILDING_GENERATORS, generate_building


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    voxel_studio_dir = script_dir  # This script lives in VoxelAssetStudio/

    # Path to the Steel City Mob Sim Unity project (repo root)
    steel_city_dir = os.path.dirname(voxel_studio_dir)
    streaming_assets = os.path.join(steel_city_dir, "Assets", "StreamingAssets")
    city_template_path = os.path.join(streaming_assets, "city_template.json")
    output_dir = os.path.join(streaming_assets, "voxel_buildings")
    layout_path = os.path.join(streaming_assets, "city_layout.json")

    # Load city template
    with open(city_template_path, "r", encoding="utf-8-sig") as f:
        template = json.load(f)

    os.makedirs(output_dir, exist_ok=True)

    # Generate buildings
    layout = {
        "_comment": "Steel City voxel building layout. Generated by generate_city_assets.py",
        "blocks": [],
        "building_types": {}
    }

    building_counter = {}  # track unique names per type

    for block_def in template["blocks"]:
        block_id = block_def["id"]
        block_row = block_def["row"]
        block_col = block_def["col"]
        block_name = block_def["name"]

        block_layout = {
            "block_id": block_id,
            "block_name": block_name,
            "row": block_row,
            "col": block_col,
            "buildings": []
        }

        # Determine block type for special rendering
        # Note: HQs are just tenement blocks (not a special building type).
        #       police_station was trimmed (no 8v door). Both flags remain
        #       in the template for gameplay logic but no longer generate
        #       special buildings.
        block_type = None

        # If this is a special block, generate that building
        if block_type:
            fname = f"{block_type}_{block_id}.stasset"
            fpath = os.path.join(output_dir, fname)
            grid, dims, meta = generate_building(block_type, seed=hash(block_id) % 10000)
            save_stasset(fpath, grid, building_meta=meta)
            block_layout["buildings"].append({
                "type": block_type,
                "stasset": f"voxel_buildings/{fname}",
                "slot": 0
            })
            layout["building_types"][block_type] = list(grid.shape)

        # Generate regular businesses
        slot = 1 if block_type else 0
        for biz_entry in block_def.get("businesses", []):
            biz_type = biz_entry["type"]
            is_illegal = biz_entry.get("illegal", False)
            count = biz_entry.get("count", 1)

            # Skip empty_land if block already has a special building
            if biz_type == "empty_land" and block_type:
                continue

            for i in range(count):
                # Generate unique filename
                base_name = biz_type
                if base_name not in building_counter:
                    building_counter[base_name] = 0
                idx = building_counter[base_name]
                building_counter[base_name] += 1

                fname = f"{base_name}_{idx}.stasset"
                fpath = os.path.join(output_dir, fname)

                # Generate the voxel building
                grid, dims, meta = generate_building(biz_type, seed=hash(f"{block_id}_{biz_type}_{i}") % 10000)

                # Save as .stasset
                save_stasset(fpath, grid, building_meta=meta)

                block_layout["buildings"].append({
                    "type": biz_type,
                    "illegal": is_illegal,
                    "stasset": f"voxel_buildings/{fname}",
                    "slot": slot
                })

                if biz_type not in layout["building_types"]:
                    layout["building_types"][biz_type] = list(grid.shape)

                slot += 1

        # If block has no buildings at all, add empty land
        if not block_layout["buildings"]:
            fname = f"empty_land_{block_id}.stasset"
            fpath = os.path.join(output_dir, fname)
            grid, dims, meta = generate_building("empty_land", seed=hash(block_id) % 10000)
            save_stasset(fpath, grid, building_meta=meta)
            block_layout["buildings"].append({
                "type": "empty_land",
                "stasset": f"voxel_buildings/{fname}",
                "slot": 0
            })
            layout["building_types"]["empty_land"] = list(grid.shape)

        layout["blocks"].append(block_layout)

    # Write layout manifest
    with open(layout_path, "w") as f:
        json.dump(layout, f, indent=2)

    print(f"\n{'='*60}")
    print(f"✅ City assets generated!")
    print(f"   Output dir: {output_dir}")
    print(f"   Layout file: {layout_path}")
    print(f"   Total blocks: {len(layout['blocks'])}")
    total_buildings = sum(len(b["buildings"]) for b in layout["blocks"])
    print(f"   Total buildings: {total_buildings}")
    print(f"   Building types: {len(layout['building_types'])}")
    for btype, dims in layout["building_types"].items():
        print(f"     {btype:20s} {dims[0]}x{dims[1]}x{dims[2]}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
